_target_: uni2ts.model.visionts.pretrain.VisionTSPretrain
module_kwargs:
  max_seq_len: 8192
min_patches: 16
min_mask_ratio: 0.1
max_mask_ratio: 0.3
max_pre_mask_ratio: 0.3
pre_mask_prob: 0.1
num_patch_input: 7
norm_const: 0.4
task_mode: impute
max_dim: 8
loss_func:
  _target_: uni2ts.loss.packed.PackedNLLLoss
lr: 1e-4
weight_decay: 1e-2
beta1: 0.9
beta2: 0.98
num_training_steps: ${mul:${trainer.max_epochs},${train_dataloader.num_batches_per_epoch}}
num_warmup_steps: 10_000
load_ckpt: true
output_dist: quantile
pixel_loss_weight: 0.0
pixel_loss_type: quantile
loss_topk: 1.0
nonlinear_dist: false
clip_input: 1
complete_no_clip: false
adapt_all_params: true
